version: '3.4'

services:
  dictionary-db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ~/temp/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=postgres